PartyInviteSite/Models/ErrorViewModel.cs
using System;

namespace PartyInviteSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PartyInviteSite/Models/GuesResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations; // Подключаем либу для проверки [Required]

namespace PartyInviteSite.Models
{
    public class GuesResponse
    {
        [Required(ErrorMessage ="Please Enter Your Name")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Enter Email")] [RegularExpression(".+\\@.+\\..+",ErrorMessage = "Enter Valid Email")]
        public string Mail { get; set; }
        [Required(ErrorMessage ="Enter Phone")]
        public int Phone { get; set; }
        [Required(ErrorMessage = "This is required field")]
        public bool? WillAttend { get; set; }
    }
}

PartyInviteSite/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PartyInviteSite.Models
{
    public static class Repository
    {
        private static List<GuesResponse> _responses = new List<GuesResponse>(); //Создаем коллекцию типа GuesResponse
        public static IEnumerable<GuesResponse> Responses //?реализуем интерфейс? хз че это
        {
            get
            {
                return _responses;  //Свойство гет, которое возвращает коллекцию GuesResponse
            }
        }
        public static void AddResponse(GuesResponse response) // Статический метод, который принимает параметры типа GuesPresonse и добавляет их в коллекцию
        {
            _responses.Add(response);

        }
    }
}

PartyInviteSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PartyInviteSite.Models;


namespace PartyInviteSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [HttpGet]
        public IActionResult Index() //Мейн страница, которая показывает время и содержит в себе ссылку на страницу регистрации
        {
            int hour = DateTime.Now.Hour;
            ViewBag.DateReturn = hour > 12 ? "Good Morning" : "Good Afternoon";
            return View();
        }
       [HttpGet]
        public IActionResult RsvpForm() //GET метод RsvpForm.cshtml (view), которая просто выводит представление
        {
          return View();
        }
        [HttpPost] 
        public IActionResult RsvpForm(GuesResponse guesResponse)//?перегруженный? POST метод, который принимает коллекцию типа GuesResponse и возвращает View Thanks.cshtml 
        {
            if (ModelState.IsValid)
            {
                Repository.AddResponse(guesResponse);
                return View("Thanks", guesResponse); // обязательно нужно передать guesResponse, иначе будет ошибка, хз еще не понял почему
            }
            else
                return View();
        }
        public IActionResult Privacy()
        {
            
            return View();
        }

        public ViewResult ListResponses()
        {
            //Linq запрос, который ?дрбавляет в коллекцию Респонсес тех, у кого вилл аттенд == тру, затем выводит в вью и передает ей значения?
            return View(Repository.Responses.Where(r => r.WillAttend == true)); ;
        }
       
    }
}

PartyInviteSite/Controllers/testController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PartyInviteSite.Controllers
{
    public class testController : Controller
    {
        //Этот контроллер чисто по приколу, для теста
        public IActionResult testGetAction()
        {
            return View("~/Views/Home/Privacy.cshtml"); //Просто преверял работает ли вызов из другой папки 
        //Если написать без указания полного пути, то нихуя не выведется, т.к должна быть соответсвующая папка вьювс (по правилам мвс)
        }
    }
}

PartyInviteSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}

<!doctype html>
<html>
<head>
    <meta name="viewport" content="widht=device-widht" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <title>PartyInviteMainPage</title>
</head>
<body>
    <div class="Mycontent" style="margin-top: 200px;">
        <div class="text-center">

            <div class="date-viewbag-return">
                @*Ебашим ретурн текущей даты системы*@
                @ViewBag.DateReturn
            </div>
            @*Это хуйня чисто для прикола, типа если день, тогда зеленый цвет, если нет, то синий*@
            @if (ViewBag.DateReturn == "Good Morning")
            {
                <style>
                    .date-viewbag-return {
                        color: chartreuse;
                    }
                </style>
            }
            else
            {
                <style>
                    .date-viewbag-return {
                        color: blue;
                    }
                </style>
            }
            <h3>The party invintation here:</h3>
            <h4>Registration below</h4>
            <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="RsvpForm">I will come</a>
        </div>
    </div>
</body>
</html>

PartyInviteSite/Views/Home/ListResponses.cshtml
@model IEnumerable<PartyInviteSite.Models.GuesResponse>

<!doctype html>
<html>
<head>
    <meta name="viewport" content="widht=device-widht" />
    <title>List of Members</title>
</head>
<body>
    <h2 align="center"> Here is the list of memers</h2>
    <table class="table"> @*Создание таблицы*@
        <thead> @*Я так понимаю вот эта хуйня - это заголовки столбцов*@
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
        </tr>
        </thead>
        <tbody> @*данные*@
            @foreach (PartyInviteSite.Models.GuesResponse r in Model) @*Прогоняем коллекцию GuesspResponse и выводим оттуда всех записавшихся, но, в котроллере идет
                                                                проверка при помощи LINQ на галочку типа bool, поэтому выводятся только типы которые "точно пойдут"*@
            {
            <tr>
                <td>@r.Name</td>
                <td>@r.Mail</td>
                <td>@r.Phone</td>
            </tr>
            }

        </tbody>
    </table>

</body>
</html>

PartyInviteSite/Views/Home/RsvpForm.cshtml
@using PartyInviteSite.Models;
@model GuesResponse

@*@model PartyInviteSite.Models.GuesResponse так тоже можно писать*@

@{
    ViewData["Title"] = "RsvpForm";
   // Layout = null;
}


<!doctype html>
<html>
<head>
    <meta name="viewport" content="widht=device-widht" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    @*<div>
        <h4>The Page About RSVP</h4>
    </div>*@
    <div class="_form-panel">
        <div class="card bg-info text-white text-center">
            <div class="card-header">RsvpForm</div>
        </div>
       <div class="card-body">
            @*p1-это отступ*@
            <form class="p-1" asp-controller="Home" asp-action="RsvpForm" method="post">
                @*Блок формы регистрации который отправляет пост запрос И ПРОЕРКА ВАЛИДНОСТИ*@
                <div asp-validation-summary="All"></div>
                <div class="form-group">
                   <label asp-for="@Model.Name">Your Name</label>
                   <input class="form-control" type="text" asp-for="@Model.Name" /> @*Таким образом ПРИВЯЗЫВАЕМ инпут к нашей модели, то есть значения будут заходить в поля модели*@
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Mail">Your Email</label>
                    <input class="form-control" type="email" asp-for="@Model.Mail" />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Phone">Your Phone</label>
                    <input class="form-control" type="tel" asp-for="@Model.Phone" />
                 </div>
                    <div class="form-group">
                        <label>Will you attend?</label>
                        <select class="form-control" asp-for="WillAttend">
                            <option value="">Choose an option</option>
                            <option value="true">Yes</option>
                            <option value="false">No</option>
                        </select>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">"Submit RSVP" </button>
                    </div>
                  
            </form>
       <form>
             <input type="submit" asp-controller="test" asp-action="testGetAction" value="Hello?" />
       </form>
        </div>
    </div>
</body>
</html>

PartyInviteSite/Views/Home/Thanks.cshtml
@using static PartyInviteSite.Models.GuesResponse

@{ 
    Layout = null;
}

<!doctype html>
<html>
<head>
    <meta name="viewport" content="widht=device-widht" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <title>Thanks</title>
</head>
<body>
    <div class="text-center" style="margin-top: 200px;">
        <h1>Thank you, @Model.Name</h1> @*Вывод имени из модели, которая была указана в форме регистрации*@
        @if (Model.WillAttend == true)@*Обычная Razor вставка, в которой реализуется условный оператор *@
        {
            @: Its greate that your are coming
        }
        else
        {
            @: Sorry to hear that
        }
        @* Click <a class="nav-link" asp-controller="Home" asp-action="ListResponses" >Here</a> to see comers *@Работает так же как и ниже
        <p>Click <a asp-action="ListResponses">Here</a> To see list     </p>   @*Ссылка на список всех заполнивших анкету*@
    </div>
    
</body>
</html>

PartyInviteSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PartyInviteSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PartyInviteSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PartyInviteSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>